export const data = [
  {
    src: "./img/podcasts/podcast-1",
    date: "14 июня",
    time: "15:43",
    title: "Европа. XIX век",
    author: "Дмитрий Гутенберг",
    views: "258",
    likes: "104",
    reposts: "68",
  },
  {
    src: "./img/podcasts/podcast-2",
    date: "11 июня",
    time: "5:32",
    title: "О музыке",
    author: "Дмитрий Гутенберг",
    views: "207",
    likes: "34",
    reposts: "18",
  },
  {
    src: "./img/podcasts/podcast-3",
    date: "8 июня",
    time: "8:54",
    title: "Люди сегодня",
    author: "Анна Васильева",
    views: "104",
    likes: "54",
    reposts: "42",
  },
  {
    src: "./img/podcasts/podcast-4",
    date: "5 июня",
    time: "9:04",
    title: "Хэллоу, Африка!",
    author: "Пётр Дмитриевский",
    views: "87",
    likes: "44",
    reposts: "5",
  },
  {
    src: "./img/podcasts/podcast-5",
    date: "2 июня",
    time: "7:03",
    title: "Обо всём",
    author: "Пётр Дмитриевский",
    views: "64",
    likes: "30",
    reposts: "8",
  },
  {
    src: "./img/podcasts/podcast-6",
    date: "28 мая",
    time: "9:15",
    title: "Физика цвета",
    author: "Татьяна Флеганова",
    views: "58",
    likes: "29",
    reposts: "14",
  },
  {
    src: "./img/podcasts/podcast-7",
    date: "22 мая",
    time: "16:04",
    title: "Источник звука",
    author: "Пётр Дмитриевский",
    views: "55",
    likes: "20",
    reposts: "12",
  },
  {
    src: "./img/podcasts/podcast-8",
    date: "18 мая",
    time: "6:55",
    title: "Правила этикета",
    author: "Татьяна Флеганова",
    views: "24",
    likes: "54",
    reposts: "42",
  },
  {
    src: "./img/podcasts/podcast-1",
    date: "14 июня",
    time: "15:43",
    title: "Европа. XIX век",
    author: "Дмитрий Гутенберг",
    views: "258",
    likes: "104",
    reposts: "68",
  },
  {
    src: "./img/podcasts/podcast-2",
    date: "11 июня",
    time: "5:32",
    title: "О музыке",
    author: "Дмитрий Гутенберг",
    views: "207",
    likes: "34",
    reposts: "18",
  },
  {
    src: "./img/podcasts/podcast-3",
    date: "8 июня",
    time: "8:54",
    title: "Люди сегодня",
    author: "Анна Васильева",
    views: "104",
    likes: "54",
    reposts: "42",
  },
  {
    src: "./img/podcasts/podcast-4",
    date: "5 июня",
    time: "9:04",
    title: "Хэллоу, Африка!",
    author: "Пётр Дмитриевский",
    views: "87",
    likes: "44",
    reposts: "5",
  },
];
